import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        revolut: {
          'canvas-dark': '#000000',
          'canvas-light': '#ffffff',
          bg: '#ffffff',
          surface: '#ffffff',
          'surface-soft': '#f4f4f4',
          'surface-elevated': '#16181a',
          'surface-deep': '#0a0a0a',
          primary: '#494fdf',
          'primary-bright': '#4f55f1',
          'primary-deep': '#3a40c4',
          'primary-hover': '#3a40c4',
          'on-primary': '#ffffff',
          border: '#e2e2e7',
          'hairline-light': '#e2e2e7',
          'hairline-dark': 'rgba(255,255,255,0.12)',
          'hairline-strong': '#191c1f',
          'divider-soft': 'rgba(255,255,255,0.06)',
          text: '#191c1f',
          ink: '#191c1f',
          body: '#1f2226',
          charcoal: '#3a3d40',
          'text-secondary': '#505a63',
          mute: '#505a63',
          ash: '#5c5e60',
          stone: '#8d969e',
          faint: '#c9c9cd',
          'on-dark': '#ffffff',
          'on-dark-mute': 'rgba(255,255,255,0.72)',
          teal: '#00a87e',
          'blue-link': '#376cd5',
          'light-blue': '#007bc2',
          'light-green': '#428619',
          'green-text': '#006400',
          yellow: '#b09000',
          warning: '#ec7e00',
          pink: '#e61e49',
          danger: '#e23b4a',
          'deep-red': '#8b0000',
          brown: '#936d62',
          success: '#34c759',
          error: '#e23b4a',
        },
      },
      borderRadius: {
        card: '20px',
        input: '12px',
        button: '9999px',
        sm: '8px',
        md: '12px',
        lg: '20px',
        xl: '28px',
      },
      fontFamily: {
        sans: ['Geist', 'system-ui', '-apple-system', 'sans-serif'],
        display: ['"Plus Jakarta Sans"', 'Geist', 'system-ui', '-apple-system', 'sans-serif'],
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};

export default config;
